[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@rari-capital/=node_modules/@rari-capital/',
    'hardhat/=node_modules/hardhat/',
    'prettier-plugin-solidity/=node_modules/prettier-plugin-solidity/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config